### ISSUE TITLE
Broken out of the box on node v8

### ISSUE THREAD

**Issue by viamin** [cucygh/vue-chrome-extension-example#4]
When setting up a fresh example using vuc init, running `npm run dev` fails.

Steps to reproduce:
1. create a new project (`mkdir fresh-vuc && cd fresh-vuc && vuc init`
2. run `npm install`
3. run `npm run dev`

Fails with:
```
$ npm run dev

> vue-chrome-extension-example@0.0.0 dev /Users/bart/Projects/fresh-vuc
> npm run dev:chrome


> vue-chrome-extension-example@0.0.0 dev:chrome /Users/bart/Projects/fresh-vuc
> gulp --watch --vendor=chrome

[08:22:28] Requiring external module babel-register
/Users/bart/Projects/fresh-vuc/node_modules/gulp-git/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/bart/Projects/fresh-vuc/node_modules/gulp-git/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/Users/bart/Projects/fresh-vuc/node_modules/gulp-git/index.js:4:18)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/bart/Projects/fresh-vuc/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```
This is on node v8.2.1 and npm v5.3.0

**Comment by viamin** [comment]
It seems to be caused by a bug in require-dir (https://github.com/aseemk/requireDir/issues/45), which is a dependency of gulp-git. 

Updating gulp-git from "1.x.x" to "2.x.x" fixes this problem.

**Comment by beupgo** [comment]
node v8+ change,you can try v7.10
